/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import javax.swing.JOptionPane;
import pilhaDuplamenteEncadeada.*;
import efeitosSonoros.*;
import java.awt.font.GlyphMetrics;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import model.bean.jogador;
import model.bean.partidas;
import model.dao.jogadorDAO;
import java.util.Date;
import model.dao.partidasDAO;
/**
 *
 * @author Igor
 */
public class telaPrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form telaPrincipal
	 */
	/**************** DATA HORA *************************/
	
	/***************************************************/
	
	private String NomeJ1;
	private String NomeJ2;
	private int vitoriasJ1 = 0;
	private int vitoriasJ2= 0;
	private int derrotasJ1 = 0;
	private int derrotasJ2 = 0;
	private String vencedor;
	private int contJogadas = 0;
	
	private boolean verificaVelha = false;
	
	private int contVitoriasJ1=0;
	private int contVitoriasJ2=0;
	private int contDerrotasJ1=0;
	private int contDerrotasJ2=0;
	
	private pilhaDuplamenteEncadeada estado = new pilhaDuplamenteEncadeada();
	
	jogador j = new jogador();
	jogadorDAO jDao = new jogadorDAO();
	partidas p = new partidas();
	partidasDAO pDao = new partidasDAO();
	
	// Static para usar em outras classes sem precisar de instancia
	static ArrayList<jogador> Jogadores = new ArrayList<jogador>();
	static ArrayList<partidas> Partidas = new ArrayList<partidas>();
	
	private jogador j1 = new jogador();
	private jogador j2 = new jogador();
	
	// Instancia para efeitos sonoros
	tocarSom ts = new tocarSom();
	public telaPrincipal() {
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn00 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoVezDe = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoJogador1 = new javax.swing.JLabel();
        campoJogador2 = new javax.swing.JLabel();
        campoVitoriasJ1 = new javax.swing.JLabel();
        campoVitoriasJ2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoIdJ1 = new javax.swing.JLabel();
        campoIdJ2 = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnLimparTabuleiro = new javax.swing.JButton();
        btnIniciaPartida = new javax.swing.JButton();
        btnDesfazJogada = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenuArquivo = new javax.swing.JMenu();
        btnMenuRank = new javax.swing.JMenuItem();
        btnMenuPartidas = new javax.swing.JMenuItem();
        btnMenuSair = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("###Jogo da Velha###");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn00.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn00.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn00.setEnabled(false);
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn02.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn02.setEnabled(false);
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn01.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn01.setEnabled(false);
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        btn12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn12.setEnabled(false);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn11.setEnabled(false);
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn10.setEnabled(false);
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn20.setEnabled(false);
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btn21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn21.setEnabled(false);
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn22.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn22.setEnabled(false);
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vez de:");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        campoVezDe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoVezDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoVezDe.setToolTipText("Campo vez de\n");
        campoVezDe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(campoVezDe, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoVezDe, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Placar");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jogador");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Vitórias");

        campoJogador1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoJogador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoJogador1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        campoJogador2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoJogador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoJogador2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        campoVitoriasJ1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoVitoriasJ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoVitoriasJ1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        campoVitoriasJ2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoVitoriasJ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoVitoriasJ2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Id");

        campoIdJ1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoIdJ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoIdJ1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        campoIdJ2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoIdJ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoIdJ2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        labelData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoIdJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoIdJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoVitoriasJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoVitoriasJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(102, 102, 102))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoVitoriasJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoVitoriasJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(campoIdJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoIdJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(labelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLimparTabuleiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimparTabuleiro.setText("Limpar Tabuleiro");
        btnLimparTabuleiro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimparTabuleiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparTabuleiro.setEnabled(false);
        btnLimparTabuleiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTabuleiroActionPerformed(evt);
            }
        });

        btnIniciaPartida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIniciaPartida.setText("Nova Partida");
        btnIniciaPartida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciaPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaPartidaActionPerformed(evt);
            }
        });

        btnDesfazJogada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDesfazJogada.setText("Desfaz Jogada");
        btnDesfazJogada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesfazJogada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDesfazJogada.setEnabled(false);
        btnDesfazJogada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesfazJogadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIniciaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnLimparTabuleiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDesfazJogada)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparTabuleiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDesfazJogada)
                    .addComponent(btnIniciaPartida))
                .addContainerGap())
        );

        btnMenuArquivo.setText("Arquivo");

        btnMenuRank.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        btnMenuRank.setText("Rank");
        btnMenuRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRankActionPerformed(evt);
            }
        });
        btnMenuArquivo.add(btnMenuRank);

        btnMenuPartidas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        btnMenuPartidas.setText("Partidas");
        btnMenuPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPartidasActionPerformed(evt);
            }
        });
        btnMenuArquivo.add(btnMenuPartidas);

        btnMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btnMenuSair.setText("Sair");
        btnMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSairActionPerformed(evt);
            }
        });
        btnMenuArquivo.add(btnMenuSair);

        jMenuBar1.add(btnMenuArquivo);

        menuSobre.setText("Sobre");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText(" Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuSobre.add(jMenuItem1);

        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaPartidaActionPerformed
        // TODO add your handling code here:
		//Random nAleatorio = new Random();
		telaEscolheNomes tEscNomes = new telaEscolheNomes(this, true);
		tEscNomes.setVisible(true);
		if(tEscNomes.getConf()){
			this.NomeJ1 = tEscNomes.getNomeJ1();
			this.NomeJ2 = tEscNomes.getNomeJ2();
			btn00.setEnabled(true);
			btn01.setEnabled(true);
			btn02.setEnabled(true);
			btn10.setEnabled(true);
			btn11.setEnabled(true);
			btn12.setEnabled(true);
			btn20.setEnabled(true);
			btn21.setEnabled(true);
			btn22.setEnabled(true);
			btnLimparTabuleiro.setEnabled(true);
			btnDesfazJogada.setEnabled(true);
			btnIniciaPartida.setEnabled(false);
			ts.tocar("inicio");
			JOptionPane.showMessageDialog(this, "Prepare-se!");
			preencheCampoVez();
			preenchePlacar();
			estado.limpaPilha();
			verificaJogador();
		}
    }//GEN-LAST:event_btnIniciaPartidaActionPerformed

    private void btnLimparTabuleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTabuleiroActionPerformed
        // TODO add your handling code here:
		btn00.setText("");
		btn01.setText("");
		btn02.setText("");
		btn10.setText("");
		btn11.setText("");
		btn12.setText("");
		btn20.setText("");
		btn21.setText("");
		btn22.setText("");
		this.contJogadas = 0;
		preencheCampoVez();
		estado.limpaPilha();
    }//GEN-LAST:event_btnLimparTabuleiroActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        // TODO add your handling code here:
		if(!(this.btn00.getText().isEmpty())){
			btn00.setText(btn00.getText());
		}
		else if(this.contJogadas%2==0){
			ts.tocar("clickX");
			this.btn00.setText("X");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn00));
		}
		else{
			ts.tocar("clickO");
			this.btn00.setText("O");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn00));
		}
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        // TODO add your handling code here:
		if(!(this.btn01.getText().isEmpty())){
			btn01.setText(btn01.getText());
		}
		else if(this.contJogadas%2==0){
			ts.tocar("clickX");
			this.btn01.setText("X");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn01));
		}
		else{
			ts.tocar("clickO");
			this.btn01.setText("O");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn01));
		}
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        // TODO add your handling code here:
		if(!(this.btn02.getText().isEmpty())){
			btn02.setText(btn02.getText());
		}
		else if(this.contJogadas%2==0){
			ts.tocar("clickX");
			this.btn02.setText("X");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn02));
		}
		else{
			ts.tocar("clickO");
			this.btn02.setText("O");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn02));
		}
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
		if(!(this.btn10.getText().isEmpty()))
			btn10.setText(btn10.getText());
		else if(this.contJogadas%2==0){
			ts.tocar("clickX");
			this.btn10.setText("X");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn10));
		}
		else{
			ts.tocar("clickO");
			this.btn10.setText("O");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn10));
		}
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
		if(!(this.btn11.getText().isEmpty()))
			btn11.setText(btn11.getText());
		else if(this.contJogadas%2==0){
			ts.tocar("clickX");
			this.btn11.setText("X");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn11));
		}
		else{
			ts.tocar("clickO");
			this.btn11.setText("O");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn11));
		}
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
		if(!(this.btn12.getText().isEmpty()))
			btn12.setText(btn12.getText());
		else if(this.contJogadas%2==0){
			ts.tocar("clickX");
			this.btn12.setText("X");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn12));
		}
		else{
			ts.tocar("clickO");
			this.btn12.setText("O");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn12));
		}
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
		if(!(this.btn20.getText().isEmpty()))
			btn20.setText(btn20.getText());
		else if(this.contJogadas%2==0){
			ts.tocar("clickX");
			this.btn20.setText("X");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn20));
		}
		else{
			ts.tocar("clickO");
			this.btn20.setText("O");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn20));
		}
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        // TODO add your handling code here:
		if(!(this.btn21.getText().isEmpty()))
			btn21.setText(btn21.getText());
		else if(this.contJogadas%2==0){
			ts.tocar("clickX");
			this.btn21.setText("X");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn21));
		}
		else{
			ts.tocar("clickO");
			this.btn21.setText("O");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn21));
		}
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
		if(!(this.btn22.getText().isEmpty()))
			btn22.setText(btn22.getText());
		else if(this.contJogadas%2==0){
			ts.tocar("clickX");
			this.btn22.setText("X");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn22));
		}
		else{
			ts.tocar("clickO");
			this.btn22.setText("O");
			this.contJogadas++;
			verificaVencedor();
			preencheCampoVez();
			estado.insereInicio(new NoPilha(null, null, btn22));
		}
    }//GEN-LAST:event_btn22ActionPerformed

    private void btnDesfazJogadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesfazJogadaActionPerformed
		tocarSom tAux = new tocarSom();
		if (this.contJogadas == 0){
			tAux.tocar("desfaz1");
			JOptionPane.showMessageDialog(this, "Pode não meu fih!!");
			return;
		}
		estado.removeFinal().getValor().setText("");
		contJogadas--;
		tAux.tocar("desfaz");
		preencheCampoVez();
    }//GEN-LAST:event_btnDesfazJogadaActionPerformed

    private void btnMenuRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRankActionPerformed
        // TODO add your handling code here:
		telaMelhoresJogadores tmjAux = new telaMelhoresJogadores(this, true);
		tmjAux.setVisible(true);
    }//GEN-LAST:event_btnMenuRankActionPerformed

    private void btnMenuPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPartidasActionPerformed
        // TODO add your handling code here:
		telaHistorico thAux = new telaHistorico(this, true);
		thAux.setVisible(true);
    }//GEN-LAST:event_btnMenuPartidasActionPerformed

    private void btnMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSairActionPerformed
        // TODO add your handling code here:
		int conf = JOptionPane.showConfirmDialog(this, "Deseja sair do jogo?");
		if(conf == JOptionPane.YES_OPTION){
			atualizaDados();
			this.dispose();
			return;
		}
    }//GEN-LAST:event_btnMenuSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
		telaSobre tSAux = new telaSobre(this, true);
		tSAux.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	
	/***************** FUNÇÕES DE CONTROLE **********************/
	public void preencheCampoVez(){
		if(this.contJogadas%2==0)
			this.campoVezDe.setText(this.NomeJ1);
		else
			this.campoVezDe.setText(this.NomeJ2);
	}
	public void preenchePlacar(){
		this.campoJogador1.setText(this.NomeJ1);
		this.campoJogador2.setText(this.NomeJ2);
		this.campoVitoriasJ1.setText(Integer.toString(this.contVitoriasJ1));
		this.campoVitoriasJ2.setText(Integer.toString(this.contVitoriasJ2));
	}
	public void atualizaPlacar(String vencedor){
		if(vencedor.equals("X")){
			JOptionPane.showMessageDialog(this, NomeJ1+" venceu a partida!");
			this.vencedor = campoJogador1.getText();
			this.contVitoriasJ1++;
			this.contDerrotasJ2++;
			preenchePlacar();
			return;
		}
		JOptionPane.showMessageDialog(this, NomeJ2+" venceu a partida!");
		this.vencedor = campoJogador2.getText();
		this.contVitoriasJ2++;
		this.contDerrotasJ1++;
		preenchePlacar();
	}
	public void verificaVencedor(){
		if(contJogadas <5)
			return;
		// Verificando as horizontais
		else if(!(btn00.getText().isEmpty())&&btn00.getText().equals(btn01.getText())&&btn01.getText().equals(btn02.getText())){
			ts.tocar("aplauso");
			atualizaPlacar(btn00.getText());
			novaPartidaConf();
		}
		else if(!(btn10.getText().isEmpty())&&btn10.getText().equals(btn11.getText())&&btn11.getText().equals(btn12.getText())){
			ts.tocar("aplauso");
			atualizaPlacar(btn00.getText());
			novaPartidaConf();
		}
		else if(!(btn20.getText().isEmpty())&&btn20.getText().equals(btn21.getText())&&btn21.getText().equals(btn22.getText())){
			ts.tocar("aplauso");
			atualizaPlacar(btn20.getText());
			novaPartidaConf();
		}
		// Verificando as verticais
		else if(!(btn00.getText().isEmpty())&&btn00.getText().equals(btn10.getText())&&btn10.getText().equals(btn20.getText())){
			ts.tocar("aplauso");
			atualizaPlacar(btn00.getText());
			novaPartidaConf();
		}
		else if(!(btn01.getText().isEmpty())&&btn01.getText().equals(btn11.getText())&&btn11.getText().equals(btn21.getText())){
			ts.tocar("aplauso");
			atualizaPlacar(btn01.getText());
			novaPartidaConf();
		}
		else if(!(btn02.getText().isEmpty())&&btn02.getText().equals(btn12.getText())&&btn12.getText().equals(btn22.getText())){
			ts.tocar("aplauso");
			atualizaPlacar(btn02.getText());
			novaPartidaConf();
		}
		// Verificando Diagonais
		else if (!(btn00.getText().isEmpty())&&btn00.getText().equals(btn11.getText())&&btn11.getText().equals(btn22.getText())){
			ts.tocar("aplauso");
			atualizaPlacar(btn00.getText());
			novaPartidaConf();
		}
		else if(!(btn02.getText().isEmpty())&&btn02.getText().equals(btn11.getText())&&btn11.getText().equals(btn20.getText())){
			ts.tocar("aplauso");
			atualizaPlacar(btn02.getText());
			novaPartidaConf();
		}
		else if(this.contJogadas==9){
			ts.tocar("velha");
			JOptionPane.showMessageDialog(this, "Velha(Empate)!");
			verificaVelha = true;
			novaPartidaConf();
		}
	}
	public void novaPartidaConf(){
		int conf = JOptionPane.showConfirmDialog(this, "Deseja jogar outra partida?");
		if(conf != JOptionPane.YES_OPTION){
			limpaTabuleiro();
			salvaPartida();
			atualizaDados();
			estadoOriginal();
			return;
		}
		salvaPartida();
		limpaTabuleiro();
	}
	public void estadoOriginal(){
		btn00.setEnabled(false);
		btn01.setEnabled(false);
		btn02.setEnabled(false);	
		btn10.setEnabled(false);
		btn11.setEnabled(false);
		btn12.setEnabled(false);
		btn20.setEnabled(false);
		btn21.setEnabled(false);
		btn22.setEnabled(false);
		btnLimparTabuleiro.setEnabled(false);
		btnDesfazJogada.setEnabled(false);
		btnIniciaPartida.setEnabled(true);
		campoJogador1.setText(null);
		campoJogador2.setText(null);
		campoVitoriasJ1.setText(null);
		campoVitoriasJ2.setText(null);
		campoVezDe.setText(null);
		campoIdJ1.setText(null);
		campoIdJ2.setText(null);
		this.NomeJ1 = null;
		this.NomeJ2 = null;
		this.contVitoriasJ1 = 0;
		this.contVitoriasJ2 = 0;
		this.contDerrotasJ1=0;
		this.contDerrotasJ2=0;
		this.vitoriasJ1 = 0;
		this.vitoriasJ2 = 0;
		estado.limpaPilha();
	}
	public void limpaTabuleiro(){
		btn00.setText("");
		btn01.setText("");
		btn02.setText("");
		btn10.setText("");
		btn11.setText("");
		btn12.setText("");
		btn20.setText("");
		btn21.setText("");
		btn22.setText("");
		this.verificaVelha = false;
		this.contJogadas = 0;
		preencheCampoVez();
		estado.limpaPilha();
	}
	public void verificaJogador(){
		boolean a = true;
		boolean b = true;
		this.Jogadores = jDao.readJogadores();	
		// Verificando jogador 1
		for(int i=0;i<Jogadores.size();i++){
			if((Jogadores.get(i).getNome().equals(this.NomeJ1))){
				System.out.println("Entrou 1");
				this.campoIdJ1.setText(Integer.toString(Jogadores.get(i).getIdJogador()));
				a = false;
				break;
			}
		}
		if(a){
			j.setNome(NomeJ1);
			j.setQtdDerrottas(0);
			j.setQtdVitorias(0);
			jDao.create(j);
			this.Jogadores = jDao.readJogadores();
			for (int i=0;i<Jogadores.size();i++){
				if(Jogadores.get(i).getNome().equals(this.NomeJ1)){
					this.campoIdJ1.setText(Integer.toString(Jogadores.get(i).getIdJogador()));
				}
			}
			System.out.println("Criado com sucesso j1");
		}
		// Verificando jogador 2
		for(int i=0;i<Jogadores.size();i++){
			if((Jogadores.get(i).getNome().equals(this.NomeJ2))){
				System.out.println("Entrou 2");
				this.campoIdJ2.setText(Integer.toString(Jogadores.get(i).getIdJogador()));
				b=false;
				break;
			}
		}
		if(b){
			j.setNome(NomeJ2);
			j.setQtdDerrottas(0);
			j.setQtdVitorias(0);
			jDao.create(j);
			this.Jogadores = jDao.readJogadores();
			for (int i=0;i<Jogadores.size();i++){
				if(Jogadores.get(i).getNome().equals(this.NomeJ2)){
					this.campoIdJ2.setText(Integer.toString(Jogadores.get(i).getIdJogador()));
				}
			}
			System.out.println("Criado com sucesso j2");
		}
	}
	public void atualizaDados(){
		this.Jogadores = jDao.readJogadores();
		jogador jAux = new jogador();
		for (int i=0;i<Jogadores.size();i++){
			if(Jogadores.get(i).getNome().equals(this.NomeJ1)){
				System.out.println("Entrou");
				jAux.setNome(NomeJ1);
				jAux.setIdJogador(Jogadores.get(i).getIdJogador());
				jAux.setQtdVitorias(Jogadores.get(i).getQtdVitorias()+this.contVitoriasJ1);
				jAux.setQtdDerrottas(Jogadores.get(i).getQtdDerrottas()+this.contDerrotasJ1);
				jAux.setIdJogador(Jogadores.get(i).getIdJogador());
				jDao.update(jAux);
				break;
			}
		}
		for (int i=0;i<Jogadores.size();i++){
			if(Jogadores.get(i).getNome().equals(this.NomeJ2)){
				System.out.println("Entrou");
				jAux.setNome(NomeJ2);
				jAux.setIdJogador(Jogadores.get(i).getIdJogador());
				jAux.setQtdVitorias(Jogadores.get(i).getQtdVitorias()+this.contVitoriasJ2);
				jAux.setQtdDerrottas(Jogadores.get(i).getQtdDerrottas()+this.contDerrotasJ2);
				jAux.setIdJogador(Jogadores.get(i).getIdJogador());
				jDao.update(jAux);
				break;
			}
		}
		System.out.println("Derrotas J1: "+this.contDerrotasJ1);
		System.out.println("Derrotas J2: "+this.contDerrotasJ2);
	}
	public void salvaPartida(){
		System.out.println("Entrou salva partidas");
		Date data = new Date();
		Date hora = new Date();
		SimpleDateFormat formato1 = new SimpleDateFormat("dd/MM/yyyy");
		SimpleDateFormat formato2 = new SimpleDateFormat("H:m:s");
		String dataFormatoBr = formato1.format(data);
		String horaFormatoBr = formato2.format(hora);
		
		// O ID da partida é AUTO_INCREMENT
		p.setJogador1(NomeJ1);
		p.setJogador2(NomeJ2);
		p.setIdJ1(Integer.parseInt(this.campoIdJ1.getText()));
		p.setIdJ2(Integer.parseInt(this.campoIdJ2.getText()));
		if(verificaVelha)
			p.setVencedor("Velha(Empate)");
		else{
			p.setVencedor(vencedor);
		}
		p.setData(dataFormatoBr);
		p.setHora(horaFormatoBr);
		pDao.create(p);
	}
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new telaPrincipal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btnDesfazJogada;
    private javax.swing.JButton btnIniciaPartida;
    private javax.swing.JButton btnLimparTabuleiro;
    private javax.swing.JMenu btnMenuArquivo;
    private javax.swing.JMenuItem btnMenuPartidas;
    private javax.swing.JMenuItem btnMenuRank;
    private javax.swing.JMenuItem btnMenuSair;
    private javax.swing.JLabel campoIdJ1;
    private javax.swing.JLabel campoIdJ2;
    private javax.swing.JLabel campoJogador1;
    private javax.swing.JLabel campoJogador2;
    private javax.swing.JLabel campoVezDe;
    private javax.swing.JLabel campoVitoriasJ1;
    private javax.swing.JLabel campoVitoriasJ2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelData;
    private javax.swing.JMenu menuSobre;
    // End of variables declaration//GEN-END:variables
}